export enum PriceProposalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DISPUTED = 'DISPUTED',
  RESOLVED_APPROVED = 'RESOLVED_APPROVED',
  RESOLVED_REJECTED = 'RESOLVED_REJECTED',
}
