name: motocare_mechanic
description: MotoCare - Giao dien Tho (demo mon Phat trien ung dung Mobile, du lieu mock, khong backend).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # (Tuy chon) Dat file Be Vietnam Pro (.ttf) vao thu muc nay de app chay offline.
  # Xem assets/google_fonts/README.txt
  assets:
    - assets/google_fonts/
